name: LernenMitTMB
authors:
  - XenoTMB
  - GondiiTMB
  - ClashiTMB
  - MaletteTMB

version: 1.0

main: tmb.learn.main.Main

commands:
  heal:
    description: Heile dich oder andere Spieler
  r:
    description: Reloade den Server
  reload:
    description: Reloade den Server
  gm:
    description: Setze deinen Gamemode um
  gamemode:
    description: Setze deinen Gamemode um
  fly:
    description: Setze deinen Flugmodus
  spawn:
    description: Teleportiere dich zum Spawn
  build:
    description: Setze deinen Baumodus um